niklaslong/matrix-elixir-sdk

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/auth.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/auth_test.exs
- test/matrix_sdk/request_test.exs
> Implement Auth API

- lib/matrix_sdk/auth.ex
- test/matrix_sdk/auth_test.exs
> Implement main auth types

- lib/matrix_sdk/auth.ex
> Add types to Auth.t()

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
> Implement server_capabilities/2

- lib/matrix_sdk/api.ex
> Update docs for server_capabilities/2

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/http_client.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/http_client_test.exs
- test/matrix_sdk/request_test.exs
> Implement room syncing

- test/matrix_sdk/api_test.exs
> Refactor API tests

- test/matrix_sdk/api_test.exs
- test/matrix_sdk/auth_test.exs
- test/matrix_sdk/http_client_test.exs
- test/matrix_sdk/request_test.exs
> Run tests asynchronously

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
> Implement getting events for a room

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/http_client.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/http_client_test.exs
- test/matrix_sdk/request_test.exs
> Implement listing rooms

- .gitignore
- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
> Implement room membership

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
> Implement room_creation/(2 & 3)

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
> Implement sending events to a room

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- lib/matrix_sdk/room_event.ex
- lib/matrix_sdk/state_event.ex
- test/matrix_sdk/room_event_test.exs
- test/matrix_sdk/state_event_test.exs
> Implement base event types

- README.md
Login with username/password
Register as guest and join room
> Basic Usage README instructions

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
Implements redact room event.
I'll be the first to admit this isn't the most elegant solution since the function has 6 params.
However, I couldn't think of a much better solution then implementing a special type for it, which feels wasteful.
Let me know what you think, happy to make any changes.
> Implement redact_room_event + tests

- lib/matrix_sdk/room_event.ex
- test/matrix_sdk/room_event_test.exs
> Remove transaction from RoomEvent

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
> Pass in auth to register_user/4

- lib/matrix_sdk/api.ex
- lib/matrix_sdk/request.ex
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/request_test.exs
Resolves #56 
Implements:
account_bind_3pid
account_delete_3pid
account_unbind_3pid
account_email_3pid_request_token
account_msisdn_3pid_request_token
The only thing I wasn't sure about was what to do with the enum types, for now I have them as strings,
> Account contact info

- README.md
- lib/matrix_sdk/client.ex
- lib/matrix_sdk/client/auth.ex
- lib/matrix_sdk/client/request.ex
- lib/matrix_sdk/client/room_event.ex
- lib/matrix_sdk/client/state_event.ex
- lib/matrix_sdk/http_client.ex
- test/matrix_sdk/client/auth_test.exs
- test/matrix_sdk/client/request_test.exs
- test/matrix_sdk/client/room_event_test.exs
- test/matrix_sdk/client/state_event_test.exs
- test/matrix_sdk/client_test.exs
- test/matrix_sdk/http_client_test.exs
> Rename and restructure project

- mix.exs
> Configure library for release on hex

- README.md
- mix.exs
This updates the docs and version numbers for 0.2.0 release.
> Prepare 0.2.0 release

- CHANGELOG.md
- README.md
- examples/guest_login.exs
- lib/matrix_sdk/api.ex
- lib/matrix_sdk/api/auth.ex
- lib/matrix_sdk/api/request.ex
- lib/matrix_sdk/api/room_event.ex
- lib/matrix_sdk/api/state_event.ex
- lib/matrix_sdk/http_client.ex
- mix.exs
- test/matrix_sdk/api/auth_test.exs
- test/matrix_sdk/api/request_test.exs
- test/matrix_sdk/api/room_event_test.exs
- test/matrix_sdk/api/state_event_test.exs
- test/matrix_sdk/api_test.exs
- test/matrix_sdk/http_client_test.exs
> Rename Client -> API
